[package]
name = "rust_script"
version = "0.1.0"
edition = "2021"


[dependencies]
bootloader = "0.11.10"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
[[bin]]
name = "rust_script"
path = "main.rs"

